name: Node CI

on:
  push:
    branches:
      - main # change to your default branch
  pull_request: {}

jobs:
  validate-and-publish:
    name: Validate and Publish
    runs-on: ubuntu-latest # only linux supported at present
    steps:
      - uses: actions/checkout@v2
      - uses: w3c/spec-prod@v2 # use the action
        with:
          W3C_ECHIDNA_TOKEN: ${{ secrets.ECHIDNA_TOKEN }}
          # Please use the URL that's appropriate for your working group!
          W3C_WG_DECISION_URL: "https://lists.w3.org/Archives/Public/public-webapps/2014JulSep/0627.html"
          W3C_NOTIFICATIONS_CC: "${{ secrets.CC }}"
          VALIDATE_LINKS: true # Validate links and cross references; default: true
          VALIDATE_MARKUP: true # Validate HTML markup; default: true
          W3C_BUILD_OVERRIDE: |
            specStatus: NOTE
